spring:
  codec:
    max-in-memory-size: 16MB
  application:
    name: connect-example-client
  flyway:
    enabled: false
  jackson:
    locale: zh_CN
    time-zone: "Asia/Shanghai"
  config:
    import: optional:classpath:github-stars-summary.yaml[.yaml]
  thymeleaf:
    mode: TEXT
    suffix: .md
logging:
  level:
    pro.chenggang: DEBUG