spring:
  application:
    name: connect-example-client
  flyway:
    enabled: false
  jackson:
    locale: zh_CN
    time-zone: "Asia/Shanghai"
  config:
    import: optional:classpath:github-stars-summary.yaml[.yaml]
logging:
  level:
    pro.chenggang: DEBUG